### ISSUE TITLE
CSVで商品登録の実装をやめる

### ISSUE THREAD

**Issue by Myplanair** [gomamisotest/cd_shop#10]
@tenchan18 @itasakashogo 
CSVで商品の新規追加や既存分のアップデートを実施する予定でしたが、
本当にこれを実装すべきか悩んでいます。

■CSV で実装したときの懸念点
・CSV でインポートする時に、タイトル名やアーティストが重複するか調べる必要があり、
枚行ごとにクエリーが飛んでしまう。そのため、商品数が膨大になるにつれて、インポートの処理が重くなる。

考えた解決策
-------------------------
■初期データの登録はseed-fu (メンターに教えてもらったGem)で実施する。
■新規の追加や編集は手入力で行う。

どうしましょうか？
ちなみにcsv でやるなら淡々と実装するだけです。（特に課題もなさそう）

**Comment by tenchan18** [comment]
了解しました！

**Comment by itasakashogo** [comment]
お願いします！！

**Comment by Myplanair** [comment]
昨日の通り、CSVでの実装は辞めます。。。
初期登録はseed-fu
追加登録は手動でやりますね。

できれば、追加登録を根性でCSVでやりたい気もしますが、一旦断念。

ちなみに、CSVでの読み取りが難しいのではなく、
アップロードされた複数の画像を一枚ずつ商品に登録ができずに辞めました。
```
この処理ができない。。。。
for @items do |item|
item = 個別の写真
item.属性 = CSV で読んだ値
end
```
