### ISSUE TITLE
問題点

### ISSUE THREAD

**Issue by itasakashogo** [gomamisotest/cd_shop#102]
直した方が良いと思われる点
・pagenateしたことで検索が機能しない。（メンターに聞いたがindexでやった方がいいかもって言われた）
・カートに商品が入っていたものを削除して０にした後に０のまま購入まで行けてしまう。
・配送先の住所がうまく反応しない

**Comment by itasakashogo** [comment]
カートの部分は治りました。

**Comment by Myplanair** [comment]
残り2件、修正しました。
無事に動く

**Comment by Myplanair** [comment]
全部修正クローズ
