### ISSUE TITLE
ヘッダーを作る

### ISSUE THREAD

**Issue by itasakashogo** [gomamisotest/cd_shop#14]
ログイン前後のヘッダーを作る

**Comment by itasakashogo** [comment]
@Myplanair  @tenchan18 
未ログインユーザーに関しては、閲覧のみという形でカートに入れる際もログイン画面に切り替えた方がいいですかね？
それとも、カートに入れる事はできて、購入の際に新規もしくはログインさせる形にしますか？？
ご意見くださいまし

**Comment by tenchan18** [comment]
どちらでも、いいと思います。
amazonは、後者だったと思います。
けど、サイトによって違ったと思います。

**Comment by itasakashogo** [comment]
了解です！
斎藤先生はどう思われますか？

**Comment by Myplanair** [comment]
@itasakashogo 
あれ？要件にあったような。

**Comment by Myplanair** [comment]
@itasakashogo 
> カートへの商品追加はユーザのログイン無しでは行えないこと
みたいなので、
商品追加⇒ログイン必須
購入履歴？もログイン必須かと

**Comment by itasakashogo** [comment]
ですね。見落としてました。
では、閲覧のみですね。

**Comment by Myplanair** [comment]
はい～

**Comment by itasakashogo** [comment]
作りましたが、未完了
・ログイン後のusernameを入れる
・検索ボタン
一応footerもやりました

**Comment by Myplanair** [comment]
質問と相談のラベル外しました～
またなにか、あったら貼ってください～
