### ISSUE TITLE
論理削除について

### ISSUE THREAD

**Issue by itasakashogo** [gomamisotest/cd_shop#29]
https://qiita.com/tamano/items/75bfffd64a1c9afe0dd3

これ簡単です。

**Comment by tenchan18** [comment]
論理削除は、サイトにgemを使用した方法が簡単と書いてあったので、paranoia gemを使おうと思っています。
導入自体は簡単でgemにparanoia を追加、install
該当テーブルにdelete_atカラムの追加、migrate
ユーザーモデルに対して、paranoia の許可をするために、acts_as_paranoidを追加
以上で導入自体は簡単なのでいけますが、お恥ずかしい事にviewの書き方が分からないので調べ中です。
また、実装出来てないので、testはまだ出来ていません。
申し訳ないですが、もうしこしお時間を頂きたいと思います。

参考にしたサイト
https://qiita.com/akasakas/items/f57286a1de9b6403c745
公式
https://github.com/rubysherpas/paranoia
