### ISSUE TITLE
pryとHirb

### ISSUE THREAD

**Issue by tenchan18** [gomamisotest/cd_shop#40]
参考情報程度に、聞き流してくれたらいいと思います。
pryで情報を観たときにHirbが入っていると見やすくなります。
導入方法は、サイトを見てください。
参考サイト
http://ruby-rails.hatenadiary.com/entry/20141024/1414160189

**Comment by Myplanair** [comment]
データは見やすそうですが、型が表示から消えちゃうのか。。
>  #<ActiveRecord::Relation

**Comment by tenchan18** [comment]
やはりそうでしたか、Userとってきても全部表示されないんですよね〜
見やすくなるのはいいですが、根本的に問題あるので、入れない様にしましょうか。
このIssue閉じます。
