### ISSUE TITLE
退会ボタンについて

### ISSUE THREAD

**Issue by itasakashogo** [gomamisotest/cd_shop#43]
![image](https://user-images.githubusercontent.com/37974157/40235209-80d47552-5ae4-11e8-8ec6-afe5ec360040.png)

右端に配置でもいいですかね？
下にあると少し変な気がしたので。

**Comment by Myplanair** [comment]
私は特に問題ないです〜

**Comment by tenchan18** [comment]
オッケーです！

**Comment by itasakashogo** [comment]
ご意見ありがとうございます！
