### ISSUE TITLE
5/22 板坂　作業報告

### ISSUE THREAD

**Issue by itasakashogo** [gomamisotest/cd_shop#62]
検索機能実装（admin側）
→ransackで実装してみようかな
あとは、ユーザー側から商品画面まで一度移動できるかの実装確認

17:00〜会議室でキャリアサポートの説明会で抜けます。。

**Comment by itasakashogo** [comment]
admin側は件数が少ないので実装まではできてない。
先に購入手続きのページ作る。
１：uri作成
２：HTML（ページ作成）

**Comment by itasakashogo** [comment]
配送先のページはできた。

**Comment by itasakashogo** [comment]
@Myplanair @tenchan18 
クレジットがよくわからないよ〜

**Comment by Myplanair** [comment]
クレジットってなんですかね？
検索機能にransack !賛成です〜

**Comment by itasakashogo** [comment]
@Myplanair 
https://qiita.com/trn031/items/d7684ed91178adac7932
これやりたいんですよ〜
